name: Daily Training Pipeline

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  run-training-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y librdkafka-dev
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Train Models & Push to Registry
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: python src/models/train_model.py
