[theme]
primaryColor = "#0EA5E9"
backgroundColor = "#F7FBFF"
secondaryBackgroundColor = "#E8F1F8"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
